### ISSUE TITLE
Using another sensor HELP

### ISSUE THREAD

**Issue by SERIDJ** [kyberpunk/esp-temperature-control#3]
hi @kyberpunk   thank you for a job well done!  its work well , just i want add another device sensor in my case i want use until 8 device at the same time with i2cdev library https://github.com/UncleRus/esp-idf-lib and tca9548_set_channels

so  I'd like to ask if anyone can help me figure out the "best practice" architecture for my relatively simple ESP32 application please
(mutex,pipe,...)

in this case i see u read data every cycle and then call a callback to publish means there is only one task if i want add another device like bm280 and subscribe to other topic too ... i create task for each dive of file platform_measurement_xx .... ? 

best regard :)

**Comment by SERIDJ** [comment]
@UncleRus thanks if u can help me here ...

**Comment by kyberpunk** [comment]
Hi @SERIDJ . You just need to add pin number parameter to `platform_measurement_read` function and pass it to driver call instead of the macro. Calling of function `dht_read_data` from esp-idf-lib should be stateless, so it is not a problem to call the same function with different port numbers. About architecture and concurrency - You can simply fetch data from all sensors sequentially from single task. If you need to use multiple tasks the esp-idf-lib driver implementation seems to be "task safe".

**Comment by kyberpunk** [comment]
Callback for publishing data is here just to remove dependency from measurement logic and publishing logic. You can add another callbacks and call them from the same task as I do or if you need different cycle length for each sensor you can create separate tasks. Both should work. If you want to use multiple different devices on the same I2C bus I did not try if it is really supported.

**Comment by SERIDJ** [comment]
@kyberpunk  yes i use multiple different devices on the same I2C bus and it work well using this example : 

````
#define SENSORS_CNT 2

static bme680_t sensors[SENSORS_CNT] = { 0 };
static i2c_dev_t i2cmux;
...

void task1(void *arg)
{
    // we can use i2c devices here:
    
    uint32_t duration;
    bme680_get_measurement_duration(&sensors[0], &duration);

    TickType_t last_wakeup = xTaskGetTickCount();
    bme680_values_float_t values;
    
    while (1)
    {
        for (size_t idx = 0; idx < SENSORS_CNT; idx++)
        {
            // switch mux
            tca9548_set_channels(&i2cmux, 1 << idx);
            // measure
            if (bme680_force_measurement(&sensors[0]) == ESP_OK)
            {
                vTaskDelay(duration);
                if (bme680_get_results_float(&sensors[0], &values) == ESP_OK)
                    printf("BME680 Sensor: %.2f °C, %.2f %%, %.2f hPa, %.2f Ohm\n",
                            values.temperature, values.humidity, values.pressure, values.gas_resistance);
            }
        }
        vTaskDelayUntil(&last_wakeup, 1000 / portTICK_PERIOD_MS);
    }
   
}

void task2(void *arg)
{
    // and here we can use i2c devices too
    ....
}

void app_main()
{
    ...
    ESP_ERROR_CHECK(i2cdev_init());
    
    memset(sensors, 0, sizeof(sensors));
    memset(&i2cmux, 0, sizeof(i2cmux));
    ESP_ERROR_CHECK(tca9548_init_desc(&i2cmux, PORT, MUX_ADDR, SDA_GPIO, SCL_GPIO));
    
    for (size_t i = 0; i < SENSORS_CNT; i++)
    {
        // switch i2c channel
        ESP_ERROR_CHECK(tca9548_set_channels(&i2cmux, 1 << i));
        
        // Init descriptor and device
        ESP_ERROR_CHECK(bme680_init_desc(&sensors[i], ADDR, PORT, SDA_GPIO, SCL_GPIO));
        ESP_ERROR_CHECK(bme680_init_sensor(&sensors[i]));
        ...
    }
    ...
    // create tasks
    ...
}

```

**Comment by SERIDJ** [comment]
@kyberpunk  hi please if u have time i need that in emergency if u want u can create offer in fiverr

**Comment by SERIDJ** [comment]
@kyberpunk yes so i choose to use esp-idf-lib and i have 8 task run in the same time each  have sensor variable , how i can do to store all those variable and send them with json file

![image](https://user-images.githubusercontent.com/46067255/87055283-6c3fce00-c204-11ea-8891-cb261ba91785.png)

**Comment by SERIDJ** [comment]
@UncleRus   please u can help me ? 

https://www.esp32.com/viewtopic.php?f=2&t=16477&p=62587&sid=c012155107b9b8bfb225e41142634c1a#p62587

**Comment by SERIDJ** [comment]
@kyberpunk  yes yes for me i want detect automatically number and type of senor is connect to my device for that i have 8 soft i2c BUS (that work well) i thins using setup a table of the devices found with i2canner (each bus) and how i can from this table i init sensor and get data i use one task for all or one task each sensor ... and i create one file json for each sensor or one for all sensor to send data MQTT server ....
